export const MOSTRAR_COMODIDADES_PADRE = 'MOSTRAR_COMODIDADES_PADRE';
export const MOSTRAR_COMODIDADES_HIJOS = 'MOSTRAR_COMODIDADES_HIJOS';
export const SELECCIONAR_CATEGORIA = 'SELECCIONAR_CATEGORIA';
export const SELECCIONAR_AMENIDAD = 'SELECCIONAR_AMENIDAD';
export const CONTENIDO_URL = 'CONTENIDO_URL';
export const CATEGORIA_ID = 'CATEGORIA_ID';


